spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: root
  jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect
  cors:
      allowedOrigins: http://localhost:4200
      allowedMethods: GET,POST,PUT,DELETE